# Generated by Django 5.2.8 on 2025-12-12 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabom', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_consent', models.BooleanField(default=False)),
                ('renewal_consent_timestamp', models.DateTimeField(null=True)),
                ('renewal_consent_text', models.TextField(blank=True, null=True)),
                ('checkout_session_id', models.CharField(max_length=50)),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('organization_subscription', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='indabom.organizationsubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
