# Generated by Django 5.2.8 on 2025-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabom', '0003_checkoutsessionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsessionrecord',
            name='checkout_session_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='checkoutsessionrecord',
            name='stripe_subscription_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='organizationmeta',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='stripe_price_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='organizationsubscription',
            name='stripe_subscription_id',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
