# Generated by Django 5.2.8 on 2025-12-22 14:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indabom', '0004_alter_checkoutsessionrecord_checkout_session_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='HTML content. You can use Django template variables like {{ user.first_name }}.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('message_id', models.CharField(blank=True, max_length=256, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='indabom.emailtemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['template', 'email'], name='indabom_ema_templat_c9fa98_idx'), models.Index(fields=['sent_at'], name='indabom_ema_sent_at_5810be_idx')],
            },
        ),
    ]
