version: '2.19.1'

services:
  application:
    build: .
    container_name: application
    command: gunicorn indabom.wsgi:application --workers 3 --log-level=debug --bind 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - static:/home/indabom/web/static
    expose:
      - 8000
    env_file: .env

  nginx:
     build: ./nginx
     container_name: nginx
     depends_on:
       - application
     restart: unless-stopped
     volumes:
       - static:/home/indabom/web/static
       - media:/home/indabom/web/media
     ports:
       - "80:80"
       - "443:443"

volumes:
  static:
  media:
