# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0003_distributor_distributorpart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributorpart',
            old_name='lead_time_weeks',
            new_name='lead_time_days',
        ),
    ]
