# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0004_auto_20170309_0019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributorpart',
            unique_together=set([('distributor', 'part', 'minimum_order_quantity', 'unit_cost')]),
        ),
    ]
