# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0007_auto_20170415_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributorpart',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='distributorpart',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='distributorpart',
            name='part',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
        migrations.DeleteModel(
            name='DistributorPart',
        ),
    ]
