# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0008_auto_20170415_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PartFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128)),
                ('file', models.FileField(upload_to='partfiles/')),
                ('upload_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='part',
            old_name='manufacturer',
            new_name='manufacturer_name',
        ),
        migrations.AddField(
            model_name='partfile',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom.Part'),
        ),
    ]
