# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0009_auto_20170415_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bom.Manufacturer'),
        ),
    ]
