# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0010_part_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='manufacturer_name',
        ),
    ]
