# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0011_remove_part_manufacturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpart',
            name='ncnr',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='sellerpart',
            name='nre_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
