# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0013_auto_20170415_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partfile',
            name='name',
        ),
    ]
