# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0014_remove_partfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partfile',
            name='file',
            field=models.FileField(upload_to='/partfiles'),
        ),
    ]
