# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0016_auto_20170417_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bom.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bom.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bom.Organization'),
            preserve_default=False,
        ),
    ]
